# Generated by Django 6.0.6 on 2026-07-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='saved_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
