# Generated by Django 6.0.6 on 2026-07-05 03:24

import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_alter_job_id_alter_uploadedfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.UUIDField(default=uuid_utils._uuid_utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
