# Generated by Django 6.0.6 on 2026-07-05 08:50

import uploads.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_job_transform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uploads.identifiers.new_job_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.UUIDField(default=uploads.identifiers.new_upload_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
